# .travis.yml
  
before_script:
- "mysql -uroot -e \"DELETE FROM mysql.db WHERE Db = 'test\\_%';\""
- "mysql -uroot -e \"DELETE FROM mysql.user WHERE Host = 'localhost' AND User = '';\""
- "mysql -uroot -e \"FLUSH PRIVILEGES;\""
- "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS portaldb_test DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
- "mysql -uroot -e \"GRANT ALL PRIVILEGES ON portaldb_test.* TO 'portaldb_testuser'@'localhost' IDENTIFIED BY 'portaldb_testuserpwd';\""
- "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS portaldb DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
- "mysql -uroot -e \"GRANT ALL PRIVILEGES ON portaldb.* TO 'portaldb'@'localhost' IDENTIFIED BY 'portaldb_password';\""
# Some extras for Travis-CI only
- "mysql -uroot -e \"DELETE FROM mysql.user WHERE User = 'travis';\""
- "mysql -uroot -e \"FLUSH PRIVILEGES;\""  


after_success:
- "mvn clean cobertura:cobertura coveralls:report"
  
language: java
script: "mvn clean -Pjetty.integration verify"
